# Generated by Django 3.1.7 on 2021-03-08 07:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kk', models.CharField(max_length=20)),
                ('aktif', models.CharField(choices=[('0', 'Closed'), ('1', 'Aktif')], default=1, max_length=1)),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'KK Aktif',
            },
        ),
        migrations.CreateModel(
            name='ReportShiftPerKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('foreman', models.ForeignKey(blank=True, limit_choices_to={'aktif': '1', 'status__status_id': '2'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreman', to='masterdata.masterworker')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.mastermesin')),
                ('no_kk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form_produksi.kk')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.mastershift')),
                ('team', models.ManyToManyField(blank=True, limit_choices_to={'aktif': '1', 'status__status_id': '1'}, related_name='team', to='masterdata.MasterWorker')),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Form dan Report by Shift',
                'ordering': ['production_date'],
            },
        ),
        migrations.CreateModel(
            name='DetailProductionResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil_jadi_qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hold_qc_qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('berat_unit_sample', models.DecimalField(decimal_places=2, help_text='Berat per meter/gsm/cartridge', max_digits=7)),
                ('reject', models.DecimalField(decimal_places=2, max_digits=7)),
                ('trimming', models.DecimalField(decimal_places=2, max_digits=7)),
                ('waste', models.DecimalField(decimal_places=2, max_digits=7)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_produksi.reportshiftperkk')),
                ('produk', models.ForeignKey(limit_choices_to={'tipe__tipe_id': '2'}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang')),
            ],
        ),
        migrations.CreateModel(
            name='DetailMaterialConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_awal', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('qty_tambahan', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('qty_akhir', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('bahan', models.ForeignKey(limit_choices_to={'tipe__tipe_id': '1'}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang')),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_produksi.reportshiftperkk')),
            ],
        ),
        migrations.CreateModel(
            name='DetailDowntime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('kategori', models.CharField(choices=[('1', 'Produksi'), ('2', 'Teknik'), ('3', 'Set up'), ('4', 'Mati Listrik'), ('5', 'Preventive Maintenance'), ('6', 'Lain-lain')], max_length=1)),
                ('notes', models.TextField()),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_produksi.reportshiftperkk')),
            ],
        ),
        migrations.CreateModel(
            name='FormDowntime',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Form Downtime',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
        migrations.CreateModel(
            name='FormMaterialConsumption',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Form Material Consumption',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
        migrations.CreateModel(
            name='FormProductionResults',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Form Production Results',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
        migrations.CreateModel(
            name='ReportByKK',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Report By KK',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.kk',),
        ),
    ]
