# Generated by Django 3.1.7 on 2021-03-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='dl_avail',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
