# Generated by Django 3.1.7 on 2021-03-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0002_reportshiftperkk_dl_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmaterialconsumption',
            name='qty_pemakaian',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='qty_akhir',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='qty_awal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='qty_tambahan',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='berat_unit_sample',
            field=models.DecimalField(decimal_places=1, help_text='Berat per meter/gsm/cartridge', max_digits=7),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='reject',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='trimming',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='waste',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
