# Generated by Django 3.1.7 on 2021-03-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20210308_1546'),
        ('form_produksi', '0003_auto_20210308_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='foreman',
            field=models.ForeignKey(limit_choices_to={'aktif': '1', 'status__status_id': '2'}, on_delete=django.db.models.deletion.PROTECT, related_name='foreman', to='masterdata.masterworker'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='team',
            field=models.ManyToManyField(limit_choices_to={'aktif': '1', 'status__status_id': '1'}, related_name='team', to='masterdata.MasterWorker'),
        ),
    ]
