# Generated by Django 3.1.7 on 2021-03-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0008_auto_20210308_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='qty_akhir',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='qty_awal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='qty_pemakaian',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='qty_tambahan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='berat_unit_sample',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='reject',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='trimming',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='waste',
            field=models.FloatField(default=0),
        ),
    ]
