# Generated by Django 3.1.7 on 2021-03-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0009_auto_20210315_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPerHari',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
    ]
