# Generated by Django 3.1.7 on 2021-03-17 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0011_auto_20210315_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdowntime',
            options={'verbose_name_plural': '1.3. Form Downtime'},
        ),
        migrations.AlterModelOptions(
            name='formmaterialconsumption',
            options={'verbose_name_plural': '1.2. Form Material Consumption'},
        ),
        migrations.AlterModelOptions(
            name='formproductionresults',
            options={'verbose_name_plural': '1.1. Form Production Results'},
        ),
        migrations.AlterModelOptions(
            name='reportbykk',
            options={'verbose_name_plural': '2. Report By KK'},
        ),
        migrations.AlterModelOptions(
            name='reportperwaktu',
            options={'verbose_name': '3. Report By Waktu', 'verbose_name_plural': '3. Report By Waktu'},
        ),
        migrations.AlterModelOptions(
            name='reportshiftperkk',
            options={'ordering': ['production_date'], 'verbose_name_plural': '1. Form dan Report by Shift'},
        ),
    ]
