# Generated by Django 3.1.7 on 2021-03-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0012_auto_20210317_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='pemakaian_bahan',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
