# Generated by Django 3.1.7 on 2021-03-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0013_reportshiftperkk_pemakaian_bahan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportshiftperkk',
            old_name='pemakaian_bahan',
            new_name='reject',
        ),
    ]
