# Generated by Django 3.1.7 on 2021-03-17 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_auto_20210317_1512'),
        ('form_produksi', '0016_auto_20210317_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='bahan',
            field=models.ForeignKey(limit_choices_to={'tipe': '1'}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang'),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='produk',
            field=models.ForeignKey(limit_choices_to={'tipe': '2'}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang'),
        ),
    ]
