# Generated by Django 3.1.7 on 2021-03-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_auto_20210317_1512'),
        ('form_produksi', '0017_auto_20210317_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='foreman',
            field=models.ForeignKey(limit_choices_to={'aktif': '1', 'status': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='foreman', to='masterdata.masterworker'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='team',
            field=models.ManyToManyField(limit_choices_to={'aktif': '1', 'status': 2}, related_name='team', to='masterdata.MasterWorker'),
        ),
    ]
