# Generated by Django 3.1.7 on 2021-03-24 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_auto_20210322_1159'),
        ('form_produksi', '0018_auto_20210318_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportshiftperkk',
            options={'verbose_name_plural': '1. Form dan Report by Shift'},
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='foreman',
            field=models.ForeignKey(blank=True, limit_choices_to={'aktif': '1', 'status': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreman', to='masterdata.masterworker'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='team',
            field=models.ManyToManyField(blank=True, limit_choices_to={'aktif': '1', 'status': 2}, null=True, related_name='team', to='masterdata.MasterWorker'),
        ),
    ]
