# Generated by Django 3.1.7 on 2021-03-24 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0019_auto_20210324_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailmaterialconsumption',
            name='qty_pemakaian',
        ),
    ]
