# Generated by Django 3.1.7 on 2021-03-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_auto_20210322_1159'),
        ('form_produksi', '0020_remove_detailmaterialconsumption_qty_pemakaian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='team',
            field=models.ManyToManyField(blank=True, limit_choices_to={'aktif': '1', 'status': 2}, related_name='team', to='masterdata.MasterWorker'),
        ),
    ]
