# Generated by Django 3.1.7 on 2021-03-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0022_auto_20210324_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='downtime',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='earn_hour',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='effective_hour',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='fg',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='hold',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='raw_material',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='scrap_usage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='total_hour',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='trimming',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='waste',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
