# Generated by Django 3.1.7 on 2021-04-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0018_masterbarang_lebar'),
        ('form_produksi', '0024_auto_20210330_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdowntime',
            options={'verbose_name_plural': '1.3. Downtime'},
        ),
        migrations.AlterModelOptions(
            name='formmaterialconsumption',
            options={'verbose_name_plural': '1.2. Material Consumption'},
        ),
        migrations.AlterModelOptions(
            name='formproductionresults',
            options={'verbose_name_plural': '1.1. Production Results'},
        ),
        migrations.AlterModelOptions(
            name='kk',
            options={'verbose_name_plural': '0. Daftar KK'},
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='group_barang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.mastergroup'),
        ),
    ]
