# Generated by Django 3.1.7 on 2021-04-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_mastergroup_tipe'),
        ('form_produksi', '0025_auto_20210401_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='bahan',
            field=models.ForeignKey(limit_choices_to={'tipe__in': [1, 3]}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang'),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='produk',
            field=models.ForeignKey(limit_choices_to={'tipe__in': [2, 3]}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang'),
        ),
    ]
