# Generated by Django 3.1.7 on 2021-04-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0027_auto_20210406_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='kk',
            name='is_export',
            field=models.CharField(choices=[('0', 'Lokal'), ('1', 'Eksport')], default=0, max_length=1),
        ),
    ]
