# Generated by Django 3.1.7 on 2021-04-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0024_masterbarang_aktif'),
        ('form_produksi', '0028_kk_is_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='bahan',
            field=models.ForeignKey(limit_choices_to={'aktif': 1, 'tipe__in': [1, 3]}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang'),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='produk',
            field=models.ForeignKey(limit_choices_to={'aktif': 1, 'tipe__in': [2, 3]}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang'),
        ),
    ]
