# Generated by Django 3.1.7 on 2021-04-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0030_detailpackagingreject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='downtime',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='earn_hour',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='effective_hour',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='fg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='hold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='raw_material',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='reject',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='scrap_usage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='total_hour',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='trimming',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='waste',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
