# Generated by Django 3.1.7 on 2021-04-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0032_auto_20210413_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailproductionresults',
            name='berat_unit_sample',
            field=models.FloatField(default=0, help_text='per lembar/ per kaleng/ dst', verbose_name='Berat Per Unit'),
        ),
    ]
