# Generated by Django 3.1.7 on 2021-04-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0035_auto_20210415_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='qty_akhir',
            field=models.FloatField(default=0, verbose_name='Sisa (kg)'),
        ),
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='qty_awal',
            field=models.FloatField(default=0, verbose_name='Awal (kg)'),
        ),
        migrations.AlterField(
            model_name='detailmaterialconsumption',
            name='qty_tambahan',
            field=models.FloatField(default=0, verbose_name='Tambahan (kg)'),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='reject',
            field=models.FloatField(default=0, verbose_name='Reject (kg)'),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='trimming',
            field=models.FloatField(default=0, verbose_name='Trimming (kg)'),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='waste',
            field=models.FloatField(default=0, verbose_name='Waste (kg)'),
        ),
    ]
