# Generated by Django 3.1.7 on 2021-04-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0027_auto_20210416_0924'),
        ('form_produksi', '0036_auto_20210416_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPackagingUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terpakai', models.IntegerField()),
                ('reject', models.IntegerField()),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_produksi.reportshiftperkk')),
                ('packaging', models.ForeignKey(limit_choices_to={'aktif': 1, 'tipe__in': [4]}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang')),
            ],
        ),
        migrations.DeleteModel(
            name='DetailPackagingReject',
        ),
    ]
