# Generated by Django 3.1.7 on 2021-04-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0037_auto_20210416_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaildowntime',
            name='kategori',
            field=models.CharField(choices=[('1', 'Produksi'), ('2', 'Teknik'), ('3', 'Set up'), ('4', 'Mati Listrik'), ('5', 'Preventive Maintenance'), ('6', 'Lain-lain'), ('9', 'Istirahat')], max_length=1),
        ),
    ]
