# Generated by Django 3.1.7 on 2021-04-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0038_auto_20210419_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='shift',
            field=models.CharField(choices=[('1', 'Shift 1'), ('2', 'Shift 2'), ('3', 'Shift 3')], max_length=1, verbose_name='# Shift'),
        ),
    ]
