# Generated by Django 3.1.7 on 2021-04-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0040_detailmaterialconsumption_reject_pkg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailmaterialconsumption',
            name='reject_pkg',
        ),
    ]
