# Generated by Django 3.1.7 on 2021-04-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0043_reportshiftperkk_reject_eqv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='downtime',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Jam DwTm'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='earn_hour',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Earn Hr'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='effective_hour',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Jam Eff'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='fg',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='FG (kg)'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='hold',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Hold (kg)'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='raw_material',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='RM (kg)'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='reject',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Rj (kg)'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='reject_eqv',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Rj Eqv'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='scrap_usage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Scr Usg (kg)'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='total_hour',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ttl Jam'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='trimming',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Trim (kg)'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='waste',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Wst (kg)'),
        ),
    ]
