# Generated by Django 3.1.7 on 2021-04-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0044_auto_20210423_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormDowntime',
        ),
        migrations.DeleteModel(
            name='FormMaterialConsumption',
        ),
        migrations.DeleteModel(
            name='FormProductionResults',
        ),
        migrations.CreateModel(
            name='ReportDowntime',
            fields=[
            ],
            options={
                'verbose_name_plural': '1.3. Downtime',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
        migrations.CreateModel(
            name='ReportMaterialConsumption',
            fields=[
            ],
            options={
                'verbose_name_plural': '1.2. Material Consumption',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
        migrations.CreateModel(
            name='ReportProductionResults',
            fields=[
            ],
            options={
                'verbose_name_plural': '1.1. Production Results',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
    ]
