# Generated by Django 3.1.7 on 2021-04-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0045_auto_20210423_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRejectPacakging',
            fields=[
            ],
            options={
                'verbose_name_plural': '1.4. Reject Packaging',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
    ]
