# Generated by Django 3.1.7 on 2021-04-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0046_reportrejectpacakging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportshiftperkk',
            name='team',
        ),
    ]
