# Generated by Django 3.1.7 on 2021-04-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0047_remove_reportshiftperkk_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaildowntime',
            name='kategori',
            field=models.CharField(choices=[('1', 'Produksi'), ('2', 'Teknik'), ('3', 'Set up'), ('4', 'Mati Listrik'), ('5', 'Cleaning Pabrik'), ('6', 'Lain-lain'), ('9', 'Istirahat')], max_length=1),
        ),
    ]
