# Generated by Django 3.1.7 on 2021-04-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0048_auto_20210423_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
