# Generated by Django 3.1.7 on 2021-04-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0049_auto_20210426_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='planned_down_hour',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Jam Eff'),
        ),
    ]
