# Generated by Django 3.1.7 on 2021-04-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0050_reportshiftperkk_planned_down_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportshiftperkk',
            options={'ordering': ['-start_time'], 'verbose_name_plural': '1. Form dan Report by Shift'},
        ),
    ]
