# Generated by Django 3.1.7 on 2021-04-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0051_auto_20210426_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportshiftperkk',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='reportshiftperkk',
            name='waktu_mulai',
        ),
        migrations.RemoveField(
            model_name='reportshiftperkk',
            name='waktu_selesai',
        ),
    ]
