# Generated by Django 3.1.7 on 2021-04-26 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0052_auto_20210426_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
