# Generated by Django 3.1.7 on 2021-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0053_auto_20210426_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='scrap_hasil',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Scr Hsl (kg)'),
        ),
    ]
