# Generated by Django 3.1.7 on 2021-05-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0055_auto_20210503_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kk',
            name='no_kk',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
