# Generated by Django 3.1.7 on 2021-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0057_reportshiftperkk_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='output_std',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
