# Generated by Django 3.1.7 on 2021-05-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0059_auto_20210518_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaildowntime',
            name='kategori',
            field=models.CharField(choices=[('1', 'Produksi'), ('2', 'Teknik'), ('3', 'Set up'), ('4', 'Mati Listrik'), ('5', 'Cleaning Mesin/ Warna'), ('6', 'Lain-lain'), ('9', 'Istirahat')], max_length=1),
        ),
    ]
