# Generated by Django 3.1.7 on 2021-05-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0060_auto_20210518_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailproductionresults',
            options={'verbose_name_plural': 'Detail Production Results'},
        ),
    ]
