# Generated by Django 3.1.7 on 2021-05-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0062_auto_20210521_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
