# Generated by Django 3.1.7 on 2021-05-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0063_reportshiftperkk_catatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='trial',
            field=models.BooleanField(default=False),
        ),
    ]
