# Generated by Django 3.1.7 on 2021-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0068_auto_20210525_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaildowntime',
            name='kategori',
            field=models.CharField(choices=[('PU', 'Produksi'), ('PS', 'Set up'), ('PC', 'Cleaning Mesin/ Warna'), ('TM', 'Teknik: Mekanik'), ('TE', 'Teknik: Elektrik'), ('ML', 'Mati Listrik'), ('LL', 'Lain-lain'), ('IS', 'Istirahat')], max_length=2),
        ),
    ]
