# Generated by Django 3.1.7 on 2021-06-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0070_auto_20210531_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRawMaterialPerKK',
            fields=[
            ],
            options={
                'verbose_name': 'RM1. Report Raw Material Per KK',
                'verbose_name_plural': 'RM1. Report Raw Material Per KK',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.kk',),
        ),
    ]
