# Generated by Django 3.1.7 on 2021-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0073_auto_20210615_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='kk',
            name='cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kk',
            name='trial',
            field=models.BooleanField(default=False),
        ),
    ]
