# Generated by Django 3.1.7 on 2021-06-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0074_auto_20210615_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportshiftperkk',
            name='cleaning',
        ),
        migrations.RemoveField(
            model_name='reportshiftperkk',
            name='trial',
        ),
    ]
