# Generated by Django 3.1.7 on 2021-06-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0075_auto_20210615_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPerUnit',
            fields=[
            ],
            options={
                'verbose_name': 'BOD1. Report By Unit',
                'verbose_name_plural': 'BOD1. Report By Unit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
    ]
