# Generated by Django 3.1.7 on 2021-06-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0039_auto_20210615_1458'),
        ('form_produksi', '0076_reportperunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='tipe_barang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.mastertipe'),
        ),
    ]
