# Generated by Django 3.1.7 on 2021-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0077_reportshiftperkk_tipe_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='kk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kk',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
