# Generated by Django 3.1.7 on 2021-06-22 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0079_auto_20210622_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kk',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 22, 11, 18, 43, 994887)),
        ),
    ]
