# Generated by Django 3.1.7 on 2021-06-22 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0081_auto_20210622_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kk',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
