# Generated by Django 3.1.7 on 2021-06-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0082_auto_20210622_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportrawmaterialperkk',
            options={'verbose_name': 'RM1. Report Raw Material', 'verbose_name_plural': 'RM1. Report Raw Material'},
        ),
    ]
