# Generated by Django 3.1.7 on 2021-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0083_auto_20210629_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmaterialconsumption',
            name='qty_pakai',
            field=models.FloatField(default=0, verbose_name='Pakai (kg)'),
        ),
    ]
