# Generated by Django 3.1.7 on 2021-06-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0085_auto_20210629_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='total_output',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Rj (kg)'),
        ),
    ]
