# Generated by Django 3.1.7 on 2021-07-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0086_reportshiftperkk_total_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailproductionresults',
            name='fg_lm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailproductionresults',
            name='fg_m2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='fg_lm',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='fg_m2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
