# Generated by Django 3.1.7 on 2021-07-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0087_auto_20210707_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPerMesin',
            fields=[
            ],
            options={
                'verbose_name': 'SMRY3. Report Per Mesin',
                'verbose_name_plural': 'SMRY3. Report Per Mesin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
    ]
