# Generated by Django 3.1.7 on 2021-07-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0088_reportpermesin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportperunit',
            options={'verbose_name': 'SMRY1. Report By Unit', 'verbose_name_plural': 'SMRY1. Report By Unit'},
        ),
        migrations.AlterModelOptions(
            name='reportperwaktu',
            options={'verbose_name': 'SMRY2. Report By Waktu', 'verbose_name_plural': 'SMRY2. Report By Waktu'},
        ),
    ]
