# Generated by Django 3.1.7 on 2021-07-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0089_auto_20210711_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdowntimepermesin',
            options={'verbose_name': 'DT1. Report Downtime Per Mesin', 'verbose_name_plural': 'DT1. Report Downtime Per Mesin'},
        ),
    ]
