# Generated by Django 3.1.7 on 2021-07-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0090_auto_20210711_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportbykk',
            options={'verbose_name_plural': 'SMRY4. Report By KK'},
        ),
        migrations.AlterModelOptions(
            name='reportdowntime',
            options={'verbose_name_plural': 'DT2. Report Downtime'},
        ),
    ]
