# Generated by Django 3.1.7 on 2021-07-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0091_auto_20210711_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kk',
            options={'verbose_name_plural': 'FORM1. Daftar KK'},
        ),
        migrations.AlterModelOptions(
            name='reportrejectpacakging',
            options={'verbose_name_plural': 'PKG1. Report Reject Packaging'},
        ),
        migrations.AlterModelOptions(
            name='reportshiftperkk',
            options={'ordering': ['-start_time'], 'verbose_name_plural': 'FORM2. Form dan Report by Shift'},
        ),
    ]
