# Generated by Django 3.1.7 on 2021-07-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0092_auto_20210713_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kk',
            options={'verbose_name_plural': 'A1. Daftar KK'},
        ),
        migrations.AlterModelOptions(
            name='reportshiftperkk',
            options={'ordering': ['-start_time'], 'verbose_name_plural': 'A2. Form dan Report by Shift'},
        ),
    ]
