# Generated by Django 3.1.7 on 2021-07-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0093_auto_20210713_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportmaterialconsumption',
            options={'verbose_name_plural': 'RM2. Report Material Consumption'},
        ),
        migrations.AlterModelOptions(
            name='reportproductionresults',
            options={'verbose_name_plural': 'FG1. Report Production Results'},
        ),
    ]
