# Generated by Django 3.1.7 on 2021-07-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0094_auto_20210713_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='byproduct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
