# Generated by Django 3.1.7 on 2021-07-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0095_reportshiftperkk_byproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPerMesinDetailed',
            fields=[
            ],
            options={
                'verbose_name': 'SMRY5. Report By Mesin',
                'verbose_name_plural': 'SMRY5. Report By Mesin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.kk',),
        ),
        migrations.AlterModelOptions(
            name='reportbykk',
            options={'verbose_name_plural': 'SMRY3. Report By KK'},
        ),
        migrations.AlterModelOptions(
            name='reportpermesin',
            options={'verbose_name': 'SMRY4. Report By Mesin vs Time', 'verbose_name_plural': 'SMRY4. Report By Mesin vs Time'},
        ),
    ]
