# Generated by Django 3.1.7 on 2021-07-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0096_auto_20210714_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportbykk',
            options={'verbose_name_plural': 'SM3. Report By KK'},
        ),
        migrations.AlterModelOptions(
            name='reportpermesin',
            options={'verbose_name': 'SM4. Report Mesin vs Waktu', 'verbose_name_plural': 'SM4. Report Mesin vs Waktu'},
        ),
        migrations.AlterModelOptions(
            name='reportpermesindetailed',
            options={'verbose_name': 'SM5. Report By Mesin', 'verbose_name_plural': 'SM5. Report By Mesin'},
        ),
        migrations.AlterModelOptions(
            name='reportperunit',
            options={'verbose_name': 'SM1. Report By Unit', 'verbose_name_plural': 'SM1. Report By Unit'},
        ),
        migrations.AlterModelOptions(
            name='reportperwaktu',
            options={'verbose_name': 'SM2. Report By Waktu', 'verbose_name_plural': 'SM2. Report By Waktu'},
        ),
    ]
