# Generated by Django 3.1.7 on 2021-07-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0098_reportperproductgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaildowntime',
            name='kategori',
            field=models.CharField(choices=[('PU', 'Produksi'), ('PS', 'Set up'), ('PC', 'Cleaning Mesin/ Warna'), ('TM', 'Teknik: Mekanik'), ('TE', 'Teknik: Elektrik'), ('ML', 'Mati Listrik'), ('LL', 'Lain-lain'), ('IS', 'Istirahat'), ('ID', 'Idle/ Tunggu Order')], max_length=2),
        ),
    ]
