# Generated by Django 3.1.7 on 2021-08-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0047_auto_20210806_1018'),
        ('form_produksi', '0101_auto_20210806_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportshiftperkk',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'aktif': '1', 'status': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator', to='masterdata.masterworker', verbose_name='Operator Extruder'),
        ),
        migrations.AlterField(
            model_name='reportshiftperkk',
            name='foreman',
            field=models.ForeignKey(blank=True, limit_choices_to={'aktif': '1', 'status': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreman', to='masterdata.masterworker'),
        ),
    ]
