# Generated by Django 3.1.7 on 2021-08-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0102_auto_20210810_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kk',
            name='is_export',
            field=models.CharField(choices=[('0', 'Lokal'), ('1', 'Eksport')], max_length=1),
        ),
    ]
