# Generated by Django 3.1.7 on 2021-08-24 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0103_auto_20210813_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kk',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Effective Date'),
        ),
    ]
