# Generated by Django 3.1.7 on 2021-08-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0104_auto_20210824_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailproductionresults',
            name='fg_std_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportshiftperkk',
            name='fg_mass_std',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='FG std (kg)'),
        ),
    ]
