# Generated by Django 3.1.7 on 2021-08-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0105_auto_20210826_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailproductionresults',
            name='fg_std_mass',
        ),
        migrations.AddField(
            model_name='detailproductionresults',
            name='fg_mass_std',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='fg_lm',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='fg_m2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='fg_mass',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='hold_mass',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detailproductionresults',
            name='total_output',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
