# Generated by Django 3.1.7 on 2021-08-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0052_auto_20210825_1628'),
        ('form_produksi', '0106_auto_20210826_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailFinishedGoodKK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qty', models.FloatField(blank=True, null=True, verbose_name='Order QTY (Sheet/ Pcs)')),
                ('no_kk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_produksi.kk')),
                ('produk', models.ForeignKey(limit_choices_to={'aktif': 1, 'tipe__in': [2, 3]}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang')),
            ],
        ),
    ]
