# Generated by Django 3.1.7 on 2021-08-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0108_auto_20210826_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailkkfinishedgood',
            name='order_qty',
            field=models.FloatField(default=0, verbose_name='Order QTY (Sheet/ Pcs)'),
            preserve_default=False,
        ),
    ]
