# Generated by Django 3.1.7 on 2021-08-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0109_auto_20210826_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefilledForm',
            fields=[
            ],
            options={
                'verbose_name_plural': 'A3. Form Pra-Terisi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.reportshiftperkk',),
        ),
    ]
