# Generated by Django 3.1.7 on 2021-09-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0052_auto_20210825_1628'),
        ('form_produksi', '0111_auto_20210915_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportShiftPerKK',
            new_name='ProductionForm',
        ),
        migrations.CreateModel(
            name='PrefilledForm',
            fields=[
            ],
            options={
                'verbose_name_plural': 'A3. Form Pra-Terisi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.productionform',),
        ),
        migrations.CreateModel(
            name='ReportDowntime',
            fields=[
            ],
            options={
                'verbose_name_plural': 'DT2. Report Downtime',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.productionform',),
        ),
        migrations.CreateModel(
            name='ReportDowntimePerMesin',
            fields=[
            ],
            options={
                'verbose_name': 'DT1. Report Downtime Per Mesin',
                'verbose_name_plural': 'DT1. Report Downtime Per Mesin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.productionform',),
        ),
        migrations.CreateModel(
            name='ReportMaterialConsumption',
            fields=[
            ],
            options={
                'verbose_name_plural': 'RM2. Report Material Consumption',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.productionform',),
        ),
        migrations.CreateModel(
            name='ReportPerMesin',
            fields=[
            ],
            options={
                'verbose_name': 'SM4. Report Machine vs Time',
                'verbose_name_plural': 'SM4. Report Machine vs Time',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.productionform',),
        ),
        migrations.CreateModel(
            name='ReportPerUnit',
            fields=[
            ],
            options={
                'verbose_name': 'SM1. Report By Unit',
                'verbose_name_plural': 'SM1. Report By Unit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.productionform',),
        ),
        migrations.CreateModel(
            name='ReportPerWaktu',
            fields=[
            ],
            options={
                'verbose_name': 'SM2. Report By Time Period',
                'verbose_name_plural': 'SM2. Report By Time Period',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.productionform',),
        ),
        migrations.CreateModel(
            name='ReportProductionResults',
            fields=[
            ],
            options={
                'verbose_name_plural': 'FG1. Report Production Results',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.productionform',),
        ),
        migrations.CreateModel(
            name='ReportRejectPacakging',
            fields=[
            ],
            options={
                'verbose_name_plural': 'PKG1. Report Reject Packaging',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.productionform',),
        ),
    ]
