# Generated by Django 3.1.7 on 2021-09-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0114_productionform_form_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionform',
            old_name='form_date',
            new_name='normalized_date',
        ),
    ]
