# Generated by Django 3.1.7 on 2021-10-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0073_auto_20211014_1453'),
        ('form_produksi', '0116_reportdowntimeperwaktu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailKKRawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(verbose_name='WO QTY')),
                ('bahan', models.ForeignKey(limit_choices_to={'aktif': 1, 'tipe__in': [1, 3]}, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterbarang')),
                ('no_kk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_produksi.kk')),
            ],
        ),
    ]
