# Generated by Django 3.1.7 on 2021-11-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0120_auto_20211102_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportDowntime',
        ),
        migrations.DeleteModel(
            name='ReportMaterialConsumption',
        ),
        migrations.DeleteModel(
            name='ReportProductionResults',
        ),
    ]
