# Generated by Django 3.1.7 on 2021-11-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0121_auto_20211103_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdowntimepermesin',
            options={'verbose_name': 'DT1. Report Downtime By Mesin', 'verbose_name_plural': 'DT1. Report Downtime By Mesin'},
        ),
        migrations.AlterModelOptions(
            name='reportdowntimeperwaktu',
            options={'verbose_name': 'DT2. Report Downtime By Time', 'verbose_name_plural': 'DT2. Report Downtime By Time'},
        ),
        migrations.AlterModelOptions(
            name='reportrawmaterialperkk',
            options={'verbose_name': 'RM1. Raw Material Report', 'verbose_name_plural': 'RM1. Raw Material Report'},
        ),
        migrations.AlterModelOptions(
            name='reportrejectpacakging',
            options={'verbose_name_plural': 'PKG1. Packaging Reject Report'},
        ),
        migrations.AlterField(
            model_name='detaildowntime',
            name='kategori',
            field=models.CharField(choices=[('PU', 'Production'), ('PS', 'Set up'), ('PC', 'Cleaning Color/ Machine'), ('TM', 'Technic: Mechanic'), ('TE', 'Technic: Electrical'), ('UT', 'Utility Devices'), ('ML', 'Mati Listrik/ Blackout'), ('LL', 'Lain-lain/ Others'), ('IS', 'Istirahat/ Break Time'), ('ID', 'Idle/ Tunggu Order')], max_length=2),
        ),
    ]
