# Generated by Django 3.1.7 on 2021-11-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0122_auto_20211109_1510'),
        ('form_produksi', '0122_auto_20211109_1509'),
    ]

    operations = [
    ]
