# Generated by Django 3.1.7 on 2021-11-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0123_merge_20211112_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDailyTime',
            fields=[
            ],
            options={
                'verbose_name': 'CK1. Machine Daily Time',
                'verbose_name_plural': 'CK1. Machine Daily Time',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.productionform',),
        ),
    ]
