# Generated by Django 3.1.7 on 2021-12-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0124_machinedailytime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefilledform',
            options={'verbose_name_plural': 'A3. Prefilled Form'},
        ),
    ]
