# Generated by Django 3.1.7 on 2021-12-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_maintenance', '0005_auto_20211222_1152'),
        ('form_produksi', '0128_auto_20211217_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaildowntime',
            name='form_breakdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='form_maintenance.breakdownevent'),
        ),
    ]
