# Generated by Django 3.1.7 on 2022-01-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0129_detaildowntime_form_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPerWaktuVsKK',
            fields=[
            ],
            options={
                'verbose_name': 'SMW2. Report By Time Period (WO Based)',
                'verbose_name_plural': 'SMW2. Report By Time Period (WO Based)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_produksi.kk',),
        ),
        migrations.AlterModelOptions(
            name='reportpermesindetailed',
            options={'verbose_name': 'SMW3. Report By Machine', 'verbose_name_plural': 'SMW3. Report By Machine'},
        ),
        migrations.AlterModelOptions(
            name='reportperproductgroup',
            options={'verbose_name': 'SMW4. Report By Product Group', 'verbose_name_plural': 'SMW4. Report By Product Group'},
        ),
        migrations.AlterModelOptions(
            name='reportperwaktu',
            options={'verbose_name': 'SMT2. Report By Time Period (Form Based)', 'verbose_name_plural': 'SMT2. Report By Time Period (Form Based)'},
        ),
    ]
