# Generated by Django 3.1.7 on 2021-03-08 07:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=2, unique=True)),
                ('group', models.CharField(max_length=20)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='MasterProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_id', models.CharField(max_length=1, unique=True)),
                ('profil', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Master Mesin',
            },
        ),
        migrations.CreateModel(
            name='MasterShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.CharField(max_length=1, unique=True)),
                ('shift', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MasterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=2, unique=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MasterTipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_id', models.CharField(max_length=2, unique=True)),
                ('tipe', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Master Tipe',
            },
        ),
        migrations.CreateModel(
            name='MasterUOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom_id', models.CharField(max_length=2, unique=True)),
                ('uom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MasterWarna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warna_id', models.CharField(max_length=2, unique=True)),
                ('warna', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Master Warna',
            },
        ),
        migrations.CreateModel(
            name='MasterWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('aktif', models.CharField(choices=[('1', 'Aktif'), ('0', 'Inaktif')], max_length=1)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterstatus')),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='MasterMesin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesin_id', models.CharField(max_length=2, unique=True)),
                ('mesin', models.CharField(max_length=20)),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Master Mesin',
            },
        ),
        migrations.CreateModel(
            name='MasterKapasitasMesin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dl_standar', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.mastergroup')),
                ('mesin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.mastermesin')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='MasterBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kode_barang', models.CharField(max_length=50, unique=True)),
                ('panjang', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lebar', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tebal', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.mastergroup')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterprofil')),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.mastertipe')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.masteruom')),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('warna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterwarna')),
            ],
            options={
                'verbose_name_plural': 'Master Barang',
            },
        ),
    ]
