# Generated by Django 3.1.7 on 2021-03-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastergroup',
            name='group_id',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='masterkapasitasmesin',
            name='performa',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='mastermesin',
            name='mesin_id',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='masterprofil',
            name='profil_id',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='mastertipe',
            name='tipe_id',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
