# Generated by Django 3.1.7 on 2021-03-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('masterdata', '0002_auto_20210308_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='mastermesin',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='masterworker',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
