# Generated by Django 3.1.7 on 2021-03-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20210310_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterkapasitasmesin',
            old_name='performa',
            new_name='output_ideal',
        ),
    ]
