# Generated by Django 3.1.7 on 2021-03-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_auto_20210310_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkapasitasmesin',
            name='output_ideal',
            field=models.FloatField(default=0),
        ),
    ]
