# Generated by Django 3.1.7 on 2021-03-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20210315_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterstatus',
            name='status_id',
        ),
    ]
