# Generated by Django 3.1.7 on 2021-03-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_produksi', '0016_auto_20210317_1508'),
        ('masterdata', '0007_remove_masterstatus_status_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterShift',
        ),
        migrations.RemoveField(
            model_name='mastermesin',
            name='mesin_id',
        ),
    ]
