# Generated by Django 3.1.7 on 2021-03-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_auto_20210317_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastergroup',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='masterproperty',
            name='prop_id',
        ),
        migrations.RemoveField(
            model_name='mastertipe',
            name='tipe_id',
        ),
        migrations.RemoveField(
            model_name='masteruom',
            name='uom_id',
        ),
        migrations.RemoveField(
            model_name='masterwarna',
            name='warna_id',
        ),
    ]
