# Generated by Django 3.1.7 on 2021-03-19 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_auto_20210317_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkapasitasmesin',
            name='warna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterwarna'),
            preserve_default=False,
        ),
    ]
