# Generated by Django 3.1.7 on 2021-03-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_masterkapasitasmesin_warna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterbarang',
            name='warna',
        ),
    ]
