# Generated by Django 3.1.7 on 2021-04-05 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_mastergroup_tipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterkapasitasmesin',
            name='prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterproperty'),
        ),
    ]
