# Generated by Django 3.1.7 on 2021-04-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0020_masterkapasitasmesin_prop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkapasitasmesin',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.mastergroup'),
        ),
        migrations.AlterField(
            model_name='masterkapasitasmesin',
            name='warna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masterwarna'),
        ),
    ]
