# Generated by Django 3.1.7 on 2021-04-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0022_masterkapasitasmesin_tebal_aux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterkapasitasmesin',
            old_name='tebal_aux',
            new_name='dimensi_aux',
        ),
    ]
