# Generated by Django 3.1.7 on 2021-04-13 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0024_masterbarang_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbarang',
            name='gsm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='masterbarang',
            name='lebar_ext',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
