# Generated by Django 3.1.7 on 2021-04-16 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0026_auto_20210416_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='gsm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='GSM (gram/m^2)'),
        ),
    ]
