# Generated by Django 3.1.7 on 2021-04-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0030_auto_20210421_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastermesin',
            name='mesin',
            field=models.CharField(max_length=30),
        ),
    ]
