# Generated by Django 3.1.7 on 2021-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0031_auto_20210421_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastergroup',
            name='group',
            field=models.CharField(max_length=30),
        ),
    ]
