# Generated by Django 3.1.7 on 2021-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0032_auto_20210421_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbarang',
            name='bobot_reject',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bobot Reject (OCI only)'),
        ),
    ]
