# Generated by Django 3.1.7 on 2021-05-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0033_masterbarang_bobot_reject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterProperty',
            new_name='MasterItemProperty',
        ),
        migrations.AlterModelOptions(
            name='masteritemproperty',
            options={'verbose_name_plural': 'Master Item Property'},
        ),
    ]
