# Generated by Django 3.1.7 on 2021-05-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0034_auto_20210510_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbarang',
            name='user_group_aux',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
