# Generated by Django 3.1.7 on 2021-05-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0035_masterbarang_user_group_aux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterkapasitasmesin',
            name='dl_standar',
            field=models.FloatField(verbose_name='DL Standar (Person)'),
        ),
    ]
