# Generated by Django 3.1.7 on 2021-05-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0036_auto_20210517_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterbarang',
            name='user_group_aux',
        ),
    ]
