# Generated by Django 3.1.7 on 2021-06-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0040_mastergroup_kategori_rm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastergroup',
            name='kategori_rm',
            field=models.CharField(blank=True, choices=[('frs', 'Fresh'), ('scr', 'Scrap'), ('pgm', 'Pigment'), ('adt', 'Aditif'), ('flr', 'Filler'), ('adk', 'Adukan'), ('rpl', 'Repellet'), ('msk', 'Masking')], max_length=3, null=True),
        ),
    ]
