# Generated by Django 3.1.7 on 2021-07-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0042_auto_20210726_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterbarang',
            options={'verbose_name_plural': 'Master Item'},
        ),
        migrations.AlterModelOptions(
            name='masterkapasitasmesin',
            options={'verbose_name_plural': 'Master Machine Capacity'},
        ),
        migrations.AlterModelOptions(
            name='mastermesin',
            options={'verbose_name_plural': 'Master Machine'},
        ),
    ]
