# Generated by Django 3.1.7 on 2021-07-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0043_auto_20210726_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastergroup',
            options={'verbose_name_plural': 'Master Item Group'},
        ),
        migrations.AlterModelOptions(
            name='mastertipe',
            options={'verbose_name_plural': 'Master Item Type'},
        ),
        migrations.AlterModelOptions(
            name='masteruom',
            options={'verbose_name_plural': 'Master UOM'},
        ),
        migrations.AlterModelOptions(
            name='masterwarna',
            options={'verbose_name_plural': 'Master Color'},
        ),
    ]
