# Generated by Django 3.1.7 on 2021-07-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0044_auto_20210726_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterstatus',
            options={'verbose_name_plural': 'Master Worker Status'},
        ),
        migrations.AlterModelOptions(
            name='masterworker',
            options={'verbose_name_plural': 'Master Workers'},
        ),
    ]
