# Generated by Django 3.1.7 on 2021-07-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0045_auto_20210726_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterwarna',
            options={'verbose_name_plural': 'Master Item Color'},
        ),
    ]
