# Generated by Django 3.1.7 on 2021-08-23 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0047_auto_20210806_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='lebar',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lebar Efektif (mm)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='panjang',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Panjang (mm)'),
            preserve_default=False,
        ),
    ]
