# Generated by Django 3.1.7 on 2021-08-24 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0048_auto_20210823_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbarang',
            name='berat_standar_fg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Berat Standar (FG)'),
        ),
    ]
