# Generated by Django 3.1.7 on 2021-08-25 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0050_auto_20210825_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='lebar',
            field=models.FloatField(help_text='Lebar dalam keadaan Korugasi (Misal lebar utama Alderon 830 = 830MM)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lebar Efektif (mm)'),
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='lebar_ext',
            field=models.FloatField(blank=True, help_text='Lebar barang jika dibentangkan, seharusnya lebih besar dari lebar utama (Misal lebar bentang Alderon 830 = 892MM)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lebar Bentang (mm)'),
        ),
    ]
