# Generated by Django 3.1.7 on 2021-08-25 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0051_auto_20210825_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='lebar',
            field=models.FloatField(help_text='Lebar dalam keadaan Korugasi (Misal lebar efektif Alderon 830 = 830MM)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lebar Efektif (mm)'),
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='tebal2',
            field=models.FloatField(blank=True, help_text='Untuk ACP: lebar Aluminum Layer', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tebal Lain (mm)'),
        ),
    ]
