# Generated by Django 3.1.7 on 2021-09-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0053_groupprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupProfile',
        ),
    ]
