# Generated by Django 3.1.7 on 2021-09-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0056_auto_20210915_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupProfile',
        ),
    ]
