# Generated by Django 3.1.7 on 2021-09-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0060_auto_20210929_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='main_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_ug', to='auth.group'),
        ),
    ]
