# Generated by Django 3.1.7 on 2021-09-29 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0063_auto_20210929_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='shift_hour',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='bobot_reject',
            field=models.FloatField(blank=True, default=1000, null=True, verbose_name='Bobot Reject (OCI only)'),
        ),
    ]
