# Generated by Django 3.1.7 on 2021-09-30 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0064_auto_20210929_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='tebal1',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tebal Utama (mm) / Diameter (inch)'),
            preserve_default=False,
        ),
    ]
