# Generated by Django 3.1.7 on 2021-10-01 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0065_auto_20210930_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='tebal2',
            field=models.FloatField(blank=True, help_text='Untuk ACP: tebal Aluminum Layer', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tebal Lain (mm)'),
        ),
    ]
