# Generated by Django 3.1.7 on 2021-10-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0066_auto_20211001_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterbarang',
            name='profil',
            field=models.ManyToManyField(related_name='profil_barang', to='masterdata.MasterItemProperty'),
        ),
    ]
