# Generated by Django 3.1.7 on 2021-10-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0067_masterbarang_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterbarang',
            name='prop1',
        ),
        migrations.RemoveField(
            model_name='masterbarang',
            name='profil',
        ),
        migrations.AddField(
            model_name='masterbarang',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.masteritemproperty'),
        ),
    ]
