# Generated by Django 3.1.7 on 2021-10-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0069_auto_20211005_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayofflist',
            name='user_group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
            preserve_default=False,
        ),
    ]
