# Generated by Django 3.1.7 on 2021-10-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0070_dayofflist_user_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayofflist',
            options={'ordering': ['-off_day']},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='main_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'groupprofile__group_type': '1'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_ug', to='auth.group'),
        ),
    ]
