# Generated by Django 3.1.7 on 2021-10-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0072_groupprofile_daily_working_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofile',
            old_name='daily_working_hour',
            new_name='daily_work_hour',
        ),
    ]
