# Generated by Django 3.1.7 on 2021-10-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0073_auto_20211014_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='weekly_days',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
