# Generated by Django 3.1.7 on 2021-10-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0075_auto_20211022_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='factory_group',
            field=models.ManyToManyField(limit_choices_to={'groupprofile__group_type': '1'}, related_name='other_ug', to='auth.Group'),
        ),
    ]
