# Generated by Django 3.1.7 on 2021-10-29 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0076_auto_20211029_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='user_group',
            field=models.ForeignKey(limit_choices_to={'groupprofile__group_type': '1'}, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='mastergroup',
            name='user_group',
            field=models.ForeignKey(limit_choices_to={'groupprofile__group_type': '1'}, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='masterkapasitasmesin',
            name='user_group',
            field=models.ForeignKey(limit_choices_to={'groupprofile__group_type': '1'}, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='mastermesin',
            name='user_group',
            field=models.ForeignKey(limit_choices_to={'groupprofile__group_type': '1'}, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
