# Generated by Django 3.1.7 on 2021-12-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0080_auto_20211208_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermesin',
            name='add_date',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
