# Generated by Django 3.1.7 on 2022-01-20 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0082_auto_20211217_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterbarang',
            name='lebar',
            field=models.FloatField(help_text='Lebar dalam keadaan Korugasi (Misal lebar efektif Alderon 830 = 830MM). \nJika Pipa, isikan diameter Pipa dalam Inch', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lebar Efektif (mm) / Diameter (inch)'),
        ),
        migrations.AlterField(
            model_name='masterbarang',
            name='tebal1',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tebal Utama (mm)'),
        ),
    ]
