# Generated by Django 3.1.7 on 2022-01-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0083_auto_20220120_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masteritemproperty',
            old_name='prop',
            new_name='item_property',
        ),
        migrations.RenameField(
            model_name='masterkapasitasmesin',
            old_name='prop',
            new_name='item_property',
        ),
    ]
