# Generated by Django 3.2.11 on 2022-01-24 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_produksi', '0131_auto_20220106_1235'),
        ('masterdata', '0084_auto_20220120_1110'),
        ('auth', '0014_remove_group_group_aux'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterFormParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_parameter', models.CharField(default=None, max_length=100, verbose_name='Parameter Pengecekan')),
            ],
        ),
        migrations.CreateModel(
            name='MasterReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reject_type', models.CharField(default=None, max_length=50, verbose_name='Jenis Reject')),
                ('aspekFungsional', models.CharField(choices=[('fungsional', 'Fungsional'), ('estetika', 'Estetika')], default='pilih salah satu', max_length=50, verbose_name='Aspek Fungsional')),
                ('aspekParameter', models.CharField(choices=[('dimensi', 'Dimensi'), ('atribut', 'Atribut')], default='pilih salah satu', max_length=50, verbose_name='Aspek Parameter')),
                ('aspekCritical', models.CharField(choices=[('critical', 'Critical'), ('non_critical', 'Non Critical')], default='pilih salah satu', max_length=50, verbose_name='Aspek Critical')),
                ('item_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='masterdata.mastergroup', verbose_name='Grup Produk')),
            ],
            options={
                'verbose_name': 'Jenis Reject',
            },
        ),
        migrations.CreateModel(
            name='QCInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'OperatorQC',
            },
        ),
        migrations.CreateModel(
            name='RejectFormSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='masterdata.mastergroup', verbose_name='Grup Produk')),
                ('reject_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form_qc.masterreject', verbose_name='Jenis Reject')),
            ],
        ),
        migrations.CreateModel(
            name='QCForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='pilih salah satu', max_length=1)),
                ('inspection_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Tanggal Pengecekan')),
                ('customer', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='masterdata.masterbarang', verbose_name='Kode Barang')),
                ('item_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='masterdata.mastergroup', verbose_name='Grup Produk')),
                ('machine', models.ForeignKey(default=None, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='masterdata.mastermesin')),
                ('no_kk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form_produksi.kk', verbose_name='No KK')),
                ('qc_inspector', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form_qc.qcinspector')),
                ('user_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Unit')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterFormSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default=None, max_length=100, verbose_name='Keterangan')),
                ('item_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='masterdata.mastergroup', verbose_name='Grup Produk')),
                ('selected_field', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form_qc.masterformparameter', verbose_name='Parameter yang Dipilih')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPengecekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensi1', models.FloatField(default=None)),
                ('dimensi2', models.FloatField(default=None)),
                ('dimensi3', models.FloatField(default=None)),
                ('dimensi4', models.FloatField(default=None)),
                ('dimensi5', models.FloatField(default=None)),
                ('dimensi6', models.FloatField(default=None)),
                ('dimensi7', models.FloatField(default=None)),
                ('dimensi8', models.FloatField(default=None)),
                ('dimensi9', models.FloatField(default=None)),
                ('dimensi10', models.FloatField(default=None)),
                ('dimensi11', models.FloatField(default=None)),
                ('dimensi12', models.FloatField(default=None)),
                ('light_transmission', models.FloatField(default=None)),
                ('squareness1', models.FloatField(default=None)),
                ('squareness2', models.FloatField(default=None)),
                ('kelengkungan', models.FloatField(default=None)),
                ('bowing_max', models.FloatField(default=None)),
                ('uji_lock', models.FloatField(default=None)),
                ('gsm', models.FloatField(default=None)),
                ('machine_rpm', models.FloatField(default=None)),
                ('machine_pressure', models.FloatField(default=None)),
                ('machine_torque', models.FloatField(default=None)),
                ('uv_pinggir', models.FloatField(default=None)),
                ('uv_tengah', models.FloatField(default=None)),
                ('uv_inkjet', models.FloatField(default=None)),
                ('corona_treatment_atas', models.FloatField(default=None)),
                ('corona_treatment_bawah', models.FloatField(default=None)),
                ('tekanan_maks_burst', models.FloatField(default=None)),
                ('viskositas', models.FloatField(default=None)),
                ('solid_content', models.FloatField(default=None)),
                ('ph', models.FloatField(default=None)),
                ('rheovis_qty', models.FloatField(default=None)),
                ('fineness_pre_adjusting', models.FloatField(default=None)),
                ('fineness_post_adjusting', models.FloatField(default=None)),
                ('bonding_strength_coil_atas', models.FloatField(default=None)),
                ('bonding_strength_coil_bwh', models.FloatField(default=None)),
                ('speed_extruder_adhesive', models.FloatField(default=None)),
                ('skin_time', models.FloatField(default=None)),
                ('qc_form', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_qc.qcform')),
                ('reject', models.ManyToManyField(related_name='reject', to='form_qc.MasterReject')),
                ('reject_indecisive', models.ManyToManyField(related_name='ragu', to='form_qc.RejectFormSelection')),
            ],
            options={
                'verbose_name': 'Detail Pengecekan',
                'verbose_name_plural': 'Dtl_Pengecekan',
            },
        ),
    ]
