# Generated by Django 3.2.11 on 2022-01-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailPengecekan',
            new_name='DetailQCInspection',
        ),
        migrations.AlterModelOptions(
            name='detailqcinspection',
            options={'verbose_name': 'Detail Pengecekan', 'verbose_name_plural': 'DetailQCInspection'},
        ),
    ]
