# Generated by Django 3.2.11 on 2022-01-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0084_auto_20220120_1110'),
        ('form_qc', '0002_auto_20220124_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengecekanProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Form Pengecekan Quality',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_qc.qcform',),
        ),
        migrations.CreateModel(
            name='SettingMasterGroupQC',
            fields=[
            ],
            options={
                'verbose_name': 'SET 1. QC Parameter',
                'verbose_name_plural': 'SET 1. QC Paramater',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.mastergroup',),
        ),
    ]
