# Generated by Django 3.2.11 on 2022-01-31 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0004_auto_20220128_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pengecekanproxy',
            options={'verbose_name_plural': 'Form Pengecekan QC'},
        ),
        migrations.AddField(
            model_name='detailqcinspection',
            name='selected_fields',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_qc.parameterformselection'),
        ),
    ]
