# Generated by Django 3.2.11 on 2022-02-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0005_auto_20220131_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailqcinspection',
            name='tekanan_maks_hidrostatik',
            field=models.FloatField(default=None),
        ),
    ]
