# Generated by Django 3.2.11 on 2022-02-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0006_detailqcinspection_tekanan_maks_hidrostatik'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailqcinspection',
            name='dimensi13',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='detailqcinspection',
            name='dimensi14',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='detailqcinspection',
            name='dimensi15',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='detailqcinspection',
            name='dimensi16',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='detailqcinspection',
            name='dimensi17',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='detailqcinspection',
            name='dimensi18',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='detailqcinspection',
            name='dimensi19',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='detailqcinspection',
            name='dimensi20',
            field=models.FloatField(default=None),
        ),
    ]
