# Generated by Django 3.2.11 on 2022-02-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0008_auto_20220202_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterformselection',
            name='kategori',
            field=models.CharField(default=None, max_length=100, verbose_name='Kategori'),
        ),
    ]
