# Generated by Django 3.2.11 on 2022-02-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0010_auto_20220203_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRejectSet',
            fields=[
            ],
            options={
                'verbose_name': 'Master Reject',
                'verbose_name_plural': 'Master Reject',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_qc.masterreject',),
        ),
    ]
