# Generated by Django 3.2.11 on 2022-02-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0011_masterrejectset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingReject',
            fields=[
            ],
            options={
                'verbose_name': 'SET 2. QC Reject',
                'verbose_name_plural': 'SET 2. QC Reject',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('form_qc.masterreject',),
        ),
    ]
