# Generated by Django 3.2.11 on 2022-02-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0084_auto_20220120_1110'),
        ('form_qc', '0013_auto_20220203_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingMasterGroupQC1',
            fields=[
            ],
            options={
                'verbose_name': 'SET 2. QC Parameter',
                'verbose_name_plural': 'SET 2. QC Paramater',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masterdata.mastergroup',),
        ),
        migrations.AlterModelOptions(
            name='settingmastergroupqc',
            options={'verbose_name': 'SET 1. QC Parameter', 'verbose_name_plural': 'SET 1. QC Paramater'},
        ),
    ]
