# Generated by Django 3.2.11 on 2022-02-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0017_alter_qcform_n_pengecekan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailqcinspection',
            name='komentar',
        ),
    ]
