# Generated by Django 3.2.11 on 2022-02-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0021_alter_qcform_n_pengecekan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcform',
            name='n_pengecekan',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=None, max_length=1),
        ),
    ]
