# Generated by Django 3.2.11 on 2022-02-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0022_alter_qcform_n_pengecekan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcform',
            old_name='n_pengecekan',
            new_name='ab',
        ),
    ]
