# Generated by Django 3.2.11 on 2022-02-03 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0023_rename_n_pengecekan_qcform_ab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterformselection',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='qcform',
            name='ab',
        ),
    ]
