# Generated by Django 3.2.11 on 2022-02-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0024_auto_20220203_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterformselection',
            name='kategori',
            field=models.CharField(default=None, max_length=100, verbose_name='Kategori'),
        ),
    ]
