# Generated by Django 3.2.11 on 2022-02-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0025_parameterformselection_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcform',
            name='pengecekan_ke',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], default=None, max_length=2),
        ),
    ]
