# Generated by Django 3.2.11 on 2022-02-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0084_auto_20220120_1110'),
        ('form_qc', '0026_qcform_pengecekan_ke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcform',
            name='item_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.mastergroup', verbose_name='Grup Produk'),
        ),
        migrations.AlterUniqueTogether(
            name='qcform',
            unique_together={('pengecekan_ke', 'inspection_date')},
        ),
    ]
