# Generated by Django 3.2.11 on 2022-02-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0028_auto_20220207_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailqcinspection',
            name='rheovis_qty',
            field=models.FloatField(default=None, null=True),
        ),
    ]
