# Generated by Django 3.2.11 on 2022-02-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0030_auto_20220207_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qcform',
            options={'verbose_name': 'Form Pengecekan'},
        ),
    ]
