# Generated by Django 3.2.11 on 2022-02-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0032_auto_20220207_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi1',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi10',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi11',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi12',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi13',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi14',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi15',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi16',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi17',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi18',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi19',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi2',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi20',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi21',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi22',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi23',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi24',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi25',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi26',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi27',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi28',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi29',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi3',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi30',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi31',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi32',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi33',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi34',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi35',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi36',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi37',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi38',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi39',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi4',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi40',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi41',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi42',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi43',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi44',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi45',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi46',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi47',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi48',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi49',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi5',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi50',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi51',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi52',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi53',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi54',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi55',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi56',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi57',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi58',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi59',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi6',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi60',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi7',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi8',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='detailqcinspection',
            name='dimensi9',
            field=models.FloatField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='qcform',
            name='pengecekan_ke',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], default=None, max_length=2),
        ),
    ]
