# Generated by Django 3.2.11 on 2022-02-10 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0084_auto_20220120_1110'),
        ('form_qc', '0033_auto_20220210_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcform',
            name='inspection_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, unique=True, verbose_name='Tanggal Pengecekan'),
        ),
        migrations.AlterField(
            model_name='qcform',
            name='pengecekan_ke',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], default=0, max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='qcform',
            unique_together={('pengecekan_ke', 'inspection_date', 'machine', 'shift')},
        ),
    ]
