# Generated by Django 3.2.11 on 2022-02-10 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0034_auto_20220210_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcform',
            name='inspection_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, unique=True, verbose_name='Tanggal Pengecekan'),
        ),
    ]
