# Generated by Django 3.2.11 on 2022-02-10 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0084_auto_20220120_1110'),
        ('form_qc', '0036_qcform_inspection_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcform',
            name='inspection_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Tanggal Pengecekan'),
        ),
        migrations.AlterUniqueTogether(
            name='qcform',
            unique_together={('pengecekan_ke', 'inspection_date', 'inspection_time', 'machine', 'shift')},
        ),
    ]
