# Generated by Django 3.2.11 on 2022-02-10 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0084_auto_20220120_1110'),
        ('form_qc', '0037_auto_20220210_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcform',
            name='inspection_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Waktu Pengecekan'),
        ),
        migrations.AlterUniqueTogether(
            name='qcform',
            unique_together={('pengecekan_ke', 'inspection_date', 'machine', 'shift')},
        ),
    ]
