# Generated by Django 3.2.11 on 2022-02-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0038_auto_20220210_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailqcinspection',
            old_name='viskositas',
            new_name='viskositas_atas',
        ),
        migrations.AddField(
            model_name='detailqcinspection',
            name='viskositas_bawah',
            field=models.FloatField(default=0),
        ),
    ]
