# Generated by Django 3.2.11 on 2022-02-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0040_auto_20220211_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailqcinspection',
            name='uv_absorber',
            field=models.FloatField(default=0),
        ),
    ]
