# Generated by Django 3.2.11 on 2022-02-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_qc', '0041_detailqcinspection_uv_absorber'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailqcinspection',
            name='komentar',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='detailqcinspection',
            name='lembar',
            field=models.IntegerField(default=0),
        ),
    ]
