# Generated by Django 3.1.7 on 2021-12-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSparepart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='mastermachinepart',
            name='user_group',
        ),
        migrations.AddField(
            model_name='breakdownform',
            name='broken_sparepart',
            field=models.ManyToManyField(to='form_maintenance.MasterSparepart'),
        ),
    ]
