# Generated by Django 3.1.7 on 2021-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_maintenance', '0002_auto_20211222_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownform',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breakdownform',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
