# Generated by Django 3.1.7 on 2021-12-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_maintenance', '0003_auto_20211222_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakdownform',
            name='broken_sparepart',
        ),
        migrations.AddField(
            model_name='breakdownform',
            name='broken_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='form_maintenance.mastermachinepart'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='breakdownform',
            name='broken_part',
        ),
        migrations.AddField(
            model_name='breakdownform',
            name='broken_part',
            field=models.ManyToManyField(to='form_maintenance.MasterSparepart'),
        ),
    ]
