# Generated by Django 3.1.7 on 2021-12-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0082_auto_20211217_1440'),
        ('form_maintenance', '0004_auto_20211222_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Closed')], default='1', max_length=1)),
                ('no_form', models.CharField(max_length=32)),
                ('report_time', models.DateTimeField()),
                ('breakdown_note', models.TextField(help_text='Divisi Produksi isi sampai sini')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.mastermesin')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='BreakdownFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('breakdown_type', models.CharField(choices=[('1', 'Mechanical'), ('2', 'Electrical')], max_length=1)),
                ('fixing_note', models.TextField()),
                ('breakdown_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_maintenance.breakdownevent')),
                ('broken_part', models.ManyToManyField(to='form_maintenance.MasterSparepart')),
                ('broken_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form_maintenance.mastermachinepart')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form_maintenance.mastertechnician')),
            ],
        ),
        migrations.DeleteModel(
            name='BreakdownForm',
        ),
    ]
