# Generated by Django 3.1.7 on 2021-12-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_maintenance', '0005_auto_20211222_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterMachinePart',
            new_name='MasterMachineSection',
        ),
    ]
