# Generated by Django 3.1.7 on 2021-12-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_maintenance', '0006_auto_20211223_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterSparepart',
            new_name='MasterMachinePart',
        ),
    ]
